name: Build and Deploy to GH Pages

on:
  # Se activa cada vez que subes cambios a la rama "main"
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Usa una versi√≥n de Node recomendada

      - name: Install Dependencies
        # Instala todas las dependencias de tu package.json
        run: npm install

      - name: Build
        # Ejecuta el script "build" de tu package.json
        run: npm run build 

      - name: Deploy
        # Toma la carpeta "dist" y la publica en la rama gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 
